test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_<%= Rails.env %>:
  service: S3
  access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:secret_access_key] %>
  region: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:region] %>
  bucket: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:bucket] %>
  endpoint: 'https://sgp1.digitaloceanspaces.com'
